Separate the libs required by the server from the libs required by the tool
microsoft/vscode-python-tools-extension-template pull request #156
Opened 2023-08-28 07:28 UTC by EeyoreLee

Here's a situation that if someone installed the libs required by server, like `pygls` that incompatible with server, and also installed the tool dependencies, like `yapf` for me. Then I can't use `yapf` I installed in local to format my code. Cause if `import.Strategy` is `useBundled`, I can't use the `yapf` package I installed and if `import.Strategy` is `fromEnvironment`, the server can't launch since the `pygls` is incompatible. Separating the libs required by the server from the libs required by the tool will address it.

2023-08-28 17:43 UTC, karthiknadig commented on bundled/tool/lsp_server.py
> -def update_sys_path(path_to_add: str, strategy: str) -> None:
You need to update this in lsp_runner.py as well.

2023-08-28 17:45 UTC, karthiknadig requested changes

2023-08-28 17:45 UTC, karthiknadig commented on .gitignore
>  bundled/libs/
May be we should name this as `server-libs`

2023-08-28 17:48 UTC, karthiknadig commented
@EeyoreLee This does not really solve the problem. Suppose the server uses some version of `attrs` that `yapf` is not compatible with. Then, because the code inserts server libs at the beginning of sys path, this can still fail. It provides some isolation, but does not entirely solve this. 

The only way in those scenarios is to use either `yapf` binary via the `yapf.path` or always run `yapf` in a separate process.

2023-08-29 09:28 UTC, EeyoreLee commented
I tested something like switching `sys.module` context and `reload` it. But `reload` don't support some attributes that namespaces have been modifed like `from xx import xx`. maybe when the sub-interpreters release in python3.13 and python3.12 is deprecated, we have a great solution. Otherwise it's indeed like you said above can't solve the problem except the two ways. So I close this pr, and thanks for your code review

2023-08-29 09:28 UTC, closed without merging